# Generated by Django 6.0.5 on 2026-05-06 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, verbose_name='Год')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Приемная кампания',
                'verbose_name_plural': 'Приемные кампании',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код специальности')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('faculty', models.CharField(max_length=100, verbose_name='Факультет')),
                ('budget_places', models.PositiveSmallIntegerField(verbose_name='Бюджетные места')),
                ('paid_places', models.PositiveSmallIntegerField(default=0, verbose_name='Платные места')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('sex', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('snils', models.CharField(blank=True, max_length=14, verbose_name='СНИЛС')),
                ('passport_series', models.CharField(blank=True, max_length=4, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(blank=True, max_length=6, verbose_name='Номер паспорта')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Подано'), ('under_review', 'На рассмотрении'), ('accepted', 'Зачислен'), ('rejected', 'Отказ')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Абитуриент',
                'verbose_name_plural': 'Абитуриенты',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Первый приоритет'), (2, 'Второй приоритет'), (3, 'Третий приоритет')], verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Подано'), ('agreement_signed', 'Согласие подписано'), ('recommended', 'Рекомендован'), ('accepted', 'Зачислен')], default='draft', max_length=20, verbose_name='Статус заявления')),
                ('is_agreement_signed', models.BooleanField(default=False, verbose_name='Согласие на зачисление')),
                ('agreement_date', models.DateTimeField(blank=True, null=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='applicants.applicant', verbose_name='Абитуриент')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicants.admissioncampaign', verbose_name='Приемная кампания')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicants.specialization', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Заявление',
                'verbose_name_plural': 'Заявления',
                'ordering': ['-submission_date'],
                'unique_together': {('applicant', 'campaign', 'priority'), ('applicant', 'campaign', 'specialization')},
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='Файл')),
                ('doc_type', models.CharField(choices=[('passport', 'Паспорт'), ('diploma', 'Аттестат'), ('photo', 'Фотография'), ('snils', 'СНИЛС'), ('other', 'Прочее')], max_length=20, verbose_name='Тип документа')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False, verbose_name='Проверен')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='applicants.applicant', verbose_name='Абитуриент')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='EnrollmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, verbose_name='Номер приказа')),
                ('order_date', models.DateField(verbose_name='Дата приказа')),
                ('file', models.FileField(blank=True, null=True, upload_to='orders/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applications', models.ManyToManyField(related_name='enrollment_orders', to='applicants.application', verbose_name='Заявления')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicants.admissioncampaign', verbose_name='Приемная кампания')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
            ],
            options={
                'verbose_name': 'Приказ о зачислении',
                'verbose_name_plural': 'Приказы о зачислении',
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Предмет')),
                ('score', models.PositiveSmallIntegerField(verbose_name='Балл')),
                ('is_ege', models.BooleanField(default=True, verbose_name='ЕГЭ')),
                ('exam_date', models.DateField(blank=True, null=True, verbose_name='Дата экзамена')),
                ('document_number', models.CharField(blank=True, max_length=50, verbose_name='Номер документа')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='applicants.application', verbose_name='Заявление')),
            ],
            options={
                'verbose_name': 'Результат экзамена',
                'verbose_name_plural': 'Результаты экзаменов',
                'unique_together': {('application', 'subject')},
            },
        ),
    ]
