# Generated by Django 6.0.5 on 2026-05-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='min_score',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Мин. проходной балл'),
        ),
    ]
